// <auto-generated />
using System;
using System.Collections.Generic;
using AgendaPositiva.Web.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgendaPositiva.Web.Datos.Migraciones
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260417005500_AgregarPreguntasAdicionalesNino")]
    partial class AgregarPreguntasAdicionalesNino
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgendaPositiva.Web.Features.Admin.Auditoria.AuditoriaAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InscripcionId")
                        .HasColumnType("integer");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ValorAnterior")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ValorNuevo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("AuditoriaAdmin");
                });

            modelBuilder.Entity("AgendaPositiva.Web.Features.Admin.Auth.Domain.UsuarioAdministrador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Dictionary<string, List<string>>>("Localidades")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Nombre")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("UsuariosAdministradores");
                });

            modelBuilder.Entity("AgendaPositiva.Web.Features.Admin.Regiones.Dominio.RegionEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cupo")
                        .HasColumnType("integer");

                    b.Property<int>("EventoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Dictionary<string, List<string>>>("Localidades")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("TotalInscritos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.ToTable("RegionesEvento");
                });

            modelBuilder.Entity("AgendaPositiva.Web.Features.Admin.Regiones.Dominio.UsuarioRegion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RegionEventoId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioAdministradorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RegionEventoId");

                    b.HasIndex("UsuarioAdministradorId", "RegionEventoId")
                        .IsUnique();

                    b.ToTable("UsuarioRegiones");
                });

            modelBuilder.Entity("AgendaPositiva.Web.Features.Inscripciones.Dominio.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("CupoTotal")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Slug")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("TotalInscritos")
                        .HasColumnType("integer");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("AgendaPositiva.Web.Features.Inscripciones.Dominio.GrupoFamiliar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("GrupoFamiliar");
                });

            modelBuilder.Entity("AgendaPositiva.Web.Features.Inscripciones.Dominio.Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("DescripcionAlergia")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<int>("EventoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GrupoFamiliarId")
                        .HasColumnType("integer");

                    b.Property<string>("NecesidadesEspeciales")
                        .HasColumnType("text");

                    b.Property<bool>("ParticipaComunionAncianos")
                        .HasColumnType("boolean");

                    b.Property<int>("PersonaId")
                        .HasColumnType("integer");

                    b.Property<int?>("Relacion")
                        .HasColumnType("integer");

                    b.Property<int?>("RelacionConPersonaId")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiereAlimentacion")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiereHospedaje")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<string>("Servicios")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("TieneAlergiaAlimentaria")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.HasIndex("GrupoFamiliarId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("RelacionConPersonaId");

                    b.ToTable("Inscripciones");
                });

            modelBuilder.Entity("AgendaPositiva.Web.Features.Inscripciones.Dominio.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<int>("Genero")
                        .HasColumnType("integer");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TipoIdentificacion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TipoIdentificacion", "NumeroIdentificacion")
                        .IsUnique();

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("AgendaPositiva.Web.Features.Admin.Regiones.Dominio.RegionEvento", b =>
                {
                    b.HasOne("AgendaPositiva.Web.Features.Inscripciones.Dominio.Evento", "Evento")
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("AgendaPositiva.Web.Features.Admin.Regiones.Dominio.UsuarioRegion", b =>
                {
                    b.HasOne("AgendaPositiva.Web.Features.Admin.Regiones.Dominio.RegionEvento", "Region")
                        .WithMany("UsuarioRegiones")
                        .HasForeignKey("RegionEventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgendaPositiva.Web.Features.Admin.Auth.Domain.UsuarioAdministrador", "Usuario")
                        .WithMany("UsuarioRegiones")
                        .HasForeignKey("UsuarioAdministradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AgendaPositiva.Web.Features.Inscripciones.Dominio.Inscripcion", b =>
                {
                    b.HasOne("AgendaPositiva.Web.Features.Inscripciones.Dominio.Evento", "Evento")
                        .WithMany("Inscripciones")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgendaPositiva.Web.Features.Inscripciones.Dominio.GrupoFamiliar", "GrupoFamiliar")
                        .WithMany("Inscripciones")
                        .HasForeignKey("GrupoFamiliarId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AgendaPositiva.Web.Features.Inscripciones.Dominio.Persona", "Persona")
                        .WithMany("Inscripciones")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgendaPositiva.Web.Features.Inscripciones.Dominio.Persona", "RelacionConPersona")
                        .WithMany()
                        .HasForeignKey("RelacionConPersonaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("AgendaPositiva.Web.Features.Inscripciones.Dominio.PreguntasAdicionalesNino", "PreguntasAdicionalesNino", b1 =>
                        {
                            b1.Property<int>("InscripcionId");

                            b1.Property<string>("Eps");

                            b1.Property<bool>("ParticipaFvKids");

                            b1.Property<int?>("TipoSangre");

                            b1.HasKey("InscripcionId");

                            b1.ToTable("Inscripciones");

                            b1
                                .ToJson("PreguntasAdicionalesNino")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("InscripcionId");
                        });

                    b.Navigation("Evento");

                    b.Navigation("GrupoFamiliar");

                    b.Navigation("Persona");

                    b.Navigation("PreguntasAdicionalesNino");

                    b.Navigation("RelacionConPersona");
                });

            modelBuilder.Entity("AgendaPositiva.Web.Features.Admin.Auth.Domain.UsuarioAdministrador", b =>
                {
                    b.Navigation("UsuarioRegiones");
                });

            modelBuilder.Entity("AgendaPositiva.Web.Features.Admin.Regiones.Dominio.RegionEvento", b =>
                {
                    b.Navigation("UsuarioRegiones");
                });

            modelBuilder.Entity("AgendaPositiva.Web.Features.Inscripciones.Dominio.Evento", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("AgendaPositiva.Web.Features.Inscripciones.Dominio.GrupoFamiliar", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("AgendaPositiva.Web.Features.Inscripciones.Dominio.Persona", b =>
                {
                    b.Navigation("Inscripciones");
                });
#pragma warning restore 612, 618
        }
    }
}
